### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by ahmeducf** [ahmeducf/library#1]
- [x] Set up project skeleton
  - [x] Set up the grid layout
  - [x] Implement `Book` object
- [x] Set up main section
- [x] Set up sidebar section
  - [x] Style sidebar
  - [x] Set up form controls
    - [x] Form layout
    - [x] Clien side validation
- [x] Display library content
  - [x] Implement `displayLibraryBooks` function
  - [x] Implement `updateLibrarySummary` function
- [x] Add book to the library
  - [x] Implement `addBookToLibrary` function
- [x] Alter book state
   - [x] Implement removing book logic
   - [x] Implement altering book's read status logic
